route = {
    "homepage_route": "/pages/home/index",
    "housepage_route": "/pages/house/index",
    "mallpage_route": "/pages/mall/index",
    "minepage_route": "/pages/mine/index",
    "authpage_route": "/pages/auth/index",
    "landingpage_route": "/pages/landing/index",
    "landingDataFromBepage_route": "/pages/landingDataFromBe/index",
    "webPagepage_route": "/pages/webPage/index",
    "webPageTransferpage_route": "/pages/webPageTransfer/index",
    "healthServicepage_route": "/pages/healthService/index",
    "hotActivitiespage_route": "/pages/hotActivities/index",
    "myActivitiespage_route": "/pages/myActivities/index",
    "activityOpportunitiespage_route": "/pages/activityOpportunities/index",
    "myPrizepage_route": "/pages/myPrize/index",
    "hotTopicListpage_route": "/pages/hotTopic/list/index",
    "citySelectpage_route": "/pages/citySelect/index",
    "landingInviteHelppage_route": "/pages/landingInviteHelp/index",
    "messagepage_route": "/pages/message/index",
    "liveStudiopage_route": "/pages/home/liveStudio/index",
    "messagepage_route": "/pages/message/index",
    "messagepage_route": "/pages/message/index",
    "messagepage_route": "/pages/message/index",
    "messagepage_route": "/pages/message/index",
    "messagepage_route": "/pages/message/index"
}
